### ISSUE TITLE
Add support for timing report

### ISSUE THREAD

**Issue by jawaad-ahmad** [brata-hsdc/brata.masterserver#14]
The leader board showed the teams' duration while running through challenges. It would be nice to capture start and stop times for all attempts at all stations for a team for further analysis and to estimate and plan for wait times better. The competition's original estimate was for the entire run to go from 11:30 a.m. till around 1 p.m. even with all the stations we had and with as few problems, the total runtime did take till at least 2:30.

~~There is no need for any view or actual report for this; just capture these in the database for now. We can look into issues for analysis later.~~

This continues brata-hsdc/brata#71.

**Comment by ellerychan** [comment]
I believe the database schema new design (#4/#11) captures timestamps for all incoming events. See `PiEvent` in `piservice`.
![msdb_schema_diagram](https://cloud.githubusercontent.com/assets/6425759/9594231/6e67a590-5026-11e5-8f82-508ec777c6ec.png)

**Comment by jawaad-ahmad** [comment]
Very well. Assigned to @ellerychan to work into the initial `piservice`.

**Comment by jawaad-ahmad** [comment]
I remember seeing a duration in the database table. Is this being worked or has it been worked already? If so, is there anything remaining for it, or can it be resolved/closed?

**Comment by ellerychan** [comment]
This is implemented with the current transaction scheme.  And contrary to what the description says, this is a necessary feature, as the durations are needed as an input to the scoring.  I vote to close it.
