### ISSUE TITLE
Implement CSV Ingest

### ISSUE THREAD

**Issue by jawaad-ahmad** [brata-hsdc/brata.masterserver#28]
From [comment](../commit/3d72d964b7dca55b9f6968ce77e2c6df8ae7ff9b?diff=unified#commitcomment-13014361):

Jaron/Mike maintain some information in the spreadsheet for schools/teams that would be useful to save as a CSV and ingest into the database to reduce/eliminate manual entry on the day of the competition.

It would be good to have a dump/restore capability (exists as `pg_dump msdb > dump.sql` / `psql msdb < dump.sql` or `pg_dump msdb | bzip2 -9 > dump_`date +yyyymmdd-HHMMSS`.bz2``), and a way to ingest data from some other convenient format.

Last year's import feature had some issues. Jaron had used some raw sql scripting to jam some of the data in, and is fine working in sql if that is the way we go again.

Currently putting it off a little bit until the schema stabilizes. The full database dump and restore is a fallback that is always there, and it does just generate SQL so it could be hand edited if needed.

**Comment by jawaad-ahmad** [comment]
Are we still planning on working this? Is it still Medium-priority, or should it go up/down at all?

**Comment by ellerychan** [comment]
We may still want to import some competition day parameters this way.  We should not have to resort to raw SQL for emergencies.  The Django admin interface provides a higher level way to interact with the database if we need to.  We should strive to anticipate needs, however, and have custom screens to accomplish those tasks.

**Comment by ellerychan** [comment]
@jaron42 I am commandeering this issue to add storage of competition parameters in the database.  My plan is to store them as JSON in the Settings table.  I will also provide a method for entering the data.  The goal is to have a better method than "type the values into the admin interface."

**Comment by ellerychan** [comment]
@jaron42: I'm adding forms for entering the data.  Will see about storing to a file/loading from a file once that is complete.  As discussed before, we can just use `pg_dump` to save the SQL.  Please comment if you think this is not a sufficient solution.

I added buttons to the **index.html** page to get to the entry forms.

**Comment by ellerychan** [comment]
This issue evolved into the creation of web forms for entering and editing the challenge parameters, plus accessor methods for retrieving the challenge parameters from the Setting table.

**Comment by ellerychan** [comment]
Re-opening this issue, because I have decided we really could use CSV file import and export for the Setting table, so I will add that.

**Comment by ellerychan** [comment]
Finally added CSV export and import for the Setting table.

**Comment by ellerychan** [comment]
Delivered additional functionality in Pull Request #63
