### ISSUE TITLE
Waypoints for Launch Activity

### ISSUE THREAD

**Issue by jawaad-ahmad** [brata-hsdc/brata.masterserver#34]
This came out of the 12/16 integration meeting.

Mike - GPS coordinates from last year
DB table?
Config file that gets read in?
Settings table

**Comment by ellerychan** [comment]
This has been handled in Issue #28 **Implement CSV Ingest**.  The Launch activity parameters (the vertices and center for the 3 triangles) are input via a web form and stored in the Setting table.  There are accessor methods for retrieving the values for Launch (and the other activities).
