### ISSUE TITLE
Redesign the front-end method of database access

### ISSUE THREAD

**Issue by jawaad-ahmad** [brata-hsdc/brata.masterserver#6]
Simplify the legacy MS design and operation as follows:

Use queries against the database of raw events to total up scores, etc., compute the current state of the competition on-the-fly, and display the results as web pages.

This breaks up Issue brata-hsdc/brata#74 Part 2. Issue brata-hsdc/brata#74 was later continued as Issue #4.

**Comment by ellerychan** [comment]
Modified the issue description by changing "Use SQL queries" to "Use queries".  The Django framework hides the SQL, so there is one less additional thing to learn.

**Comment by jawaad-ahmad** [comment]
@ellerychan Where are we with this issue? Is there anything more to do for this one?

**Comment by ellerychan** [comment]
This is the description of the entire MS redesign.  I vote we close this as being too broad now.
